spring:
  profiles:
    active: dev
  application:
    name: CadastroCliente
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init.mode: always
logging:
  file:
    name: logs/cadastro-cliente.log
